// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB32eXtDRYjzdl8aj0FMK-uDfY3QR1ULyk',
    appId: '1:882377029666:web:5f01a5d7abb147e2ffb27b',
    messagingSenderId: '882377029666',
    projectId: 'officialeloquim',
    authDomain: 'officialeloquim.firebaseapp.com',
    storageBucket: 'officialeloquim.firebasestorage.app',
    measurementId: 'G-K8HDG6MHCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUJ0QlKwmVavw1Hd_nIzHpM3JoYTEnqQ',
    appId: '1:882377029666:android:77ea56c07cf0d0e7ffb27b',
    messagingSenderId: '882377029666',
    projectId: 'officialeloquim',
    storageBucket: 'officialeloquim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmyLB01ylmOGIAO_0Fgzd8bMsBpv1qeYE',
    appId: '1:882377029666:ios:ff5198d533d30484ffb27b',
    messagingSenderId: '882377029666',
    projectId: 'officialeloquim',
    storageBucket: 'officialeloquim.firebasestorage.app',
    iosBundleId: 'com.increase.eloquim',
  );

}